{% set version = '1.7.3-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scrm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/scrm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/scrm/scrm_{{ version }}.tar.gz
  sha256: c89692790c31b4778c3cb770691f7c88b990c87def588245ea44273a84d20f24

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.2
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.2

test:
  commands:
    - $R -e "library('scrm')"           # [not win]
    - "\"%R%\" -e \"library('scrm')\""  # [win]

about:
  home: https://github.com/scrm/scrm-r
  license: GPL (>= 3)
  summary: A coalescent simulator that allows the rapid simulation of biological sequences under
    neutral models of evolution. Different to other coalescent based simulations, it
    has an optional approximation parameter that allows for high accuracy while maintaining
    a linear run time cost for long sequences. It is optimized for simulating massive
    data sets as produced by Next- Generation Sequencing technologies for up to several
    thousand sequences.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: scrm
# Type: Package
# Title: Simulating the Evolution of Biological Sequences
# Version: 1.7.3-1
# Authors@R: c( person('Paul', 'Staab', , 'develop@paulstaab.de', role=c('aut', 'cre', 'cph')), person('Zhu', 'Sha', role=c('aut', 'cph')), person('Dirk', 'Metzler', role=c('aut', 'cph', 'ths')), person('Gerton', 'Lunter', role=c('aut', 'cph', 'ths')) )
# Description: A coalescent simulator that allows the rapid simulation of biological sequences under neutral models of evolution. Different to other coalescent based simulations, it has an optional approximation parameter that allows for high accuracy while maintaining a linear run time cost for long sequences. It is optimized for simulating massive data sets as produced by Next- Generation Sequencing technologies for up to several thousand sequences.
# URL: https://github.com/scrm/scrm-r
# BugReports: https://github.com/scrm/scrm-r/issues
# License: GPL (>= 3)
# Depends: R (>= 3.1.0)
# Imports: Rcpp (>= 0.11.2)
# Suggests: ape, knitr, rmarkdown, testthat (>= 0.9.0)
# SystemRequirements: C++11
# VignetteBuilder: knitr
# LinkingTo: Rcpp
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2018-11-19 20:07:22 UTC; paul
# Author: Paul Staab [aut, cre, cph], Zhu Sha [aut, cph], Dirk Metzler [aut, cph, ths], Gerton Lunter [aut, cph, ths]
# Maintainer: Paul Staab <develop@paulstaab.de>
# Repository: CRAN
# Date/Publication: 2018-11-19 20:40:03 UTC
