travis:
  secure:
    BINSTAR_TOKEN: KKbJuNt2L8tFLmZXbd4w8xI5/GoaiTybcNszHwa4hU8w9NdCtz+ZENfr35Rjk9VT6XJ4D2DPUhj8Lgqf/Qba5ugrvuuvDQYq0pg9KuTY0/BGDRO8Vxt/RpbWYZQCHJhRRCGs1eISzmlTYAOgpx9/9cGQnylXE5ra8Myzn49YekL5AU7ydcXER0XA73g1209/+y5NLDjo8eFqc6IFeU6tYi7lIqYCb73DTxvR7HgOL3bY1khVRKk0FxjS8AKca1RQBtBaLCmCHayNnsr9RP9MGQretzbnSf0J6cPvDnrrd6C/6TGpTXctVS27tDQLXfmwX/0dW3uO09QR+Nd/fLjsR4DWong6Hry3kfM3nCBLPqanXX7mgFCO0T2SxiRdfMPQs2glp7SeFpAHBT7MCafpKRHoRmtt/lj2Ua10Pwc87I+dKGhw+sIyUQ0xu92VeMeLbF4MKmrJYhVP7a3OhwiKPot0UVn1Qr7dbvN8phB2ksL2uushyqwFGMpRhCB2SSOhuGstLxMHlwgz1+74EAvrQ79t5xZB3TO5fDm+qven487f8gmd8sFrZ1sTt9F58ctiZY8lep+3KIaWJxqlnQDd/MxQ9Y4Sexqh3tpz4ISSHjZvLJRFJbDP7xrbeATvMnWmn9JRBF4L7zbEo0ia4ZQVoRTPJlIgiDMLX68z6JVHW3s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
