travis:
  secure:
    BINSTAR_TOKEN: lV+4WGYnTKx4yF5hfYF+6F46gtCXOkqv2Jvas/vFBBMgZdyLBhjDe1NHE4J4Tcf1yZa5RIWcvDd5vLOeyqYy5rYgn4EUtStvgYyT2gqSrl0iBKYklysWkJVBap1oUGppOKqZ0QxEyjCaz7TVAMX7DRU+TTJ3ez91Hgwc0tW49ZoWbb4QZByY3ZYVtJVLgN8rmMq5RJSHMgrz/pWNYa+mDWVxKLqV08Ha3OhVM2pbU2zjfWI4LBQp8b+bqlI03vwnArjHlNEqzuLMLaq745ho1W1neIYM/rclALOy55cCNCVPdJIiTMnfMY3h71Kl/fM5JIV4a5So6+HQroTaVwD4GuAZ2XIm6doHQCyDFYmDvvEE6AIRe7YE6G/ox23PHJSMGUDZs3sRdjso+iMqF/YqLXohwktHwS+zaC7hvIBKXnd3Y6uQlAlTiV9hSq+kEtBEUE5DmThf+KrHeVvsxBVIihbfJGrGU2J7MksJzfss7gJOGvjXWcYIoVC7QwoN8qzg+esOjDQgoq/dYlb4d03QRVY7BIgznEeE/RlGRSbNjtI70Rmd3SX5JP6UW4PIYDXxSmqgyLC/0NAj4Cp3xscg0DyVAbcyUrWQdpNodVdiqkqqgX2gyGnf9CuzqBEjxF1icZqIGbomyyoYSIpmsJ1Ej4JaBJqKFHN4eRO4JeWrBwo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
