travis:
  secure:
    BINSTAR_TOKEN: J05+zuCMeiCR2WgaH/LvMNtY5RzjcREgRgrVeMzcuw+SDTYTfEjOqT2fy2DLzqvyXwdEMgzZWQ4vfLa5diCnpqvRmlqibKbgD3Gkp1aJ19dZLr1MowLg5DmQZXWkHcjDYt7BORBpNZuYqRWNmWbRGibAVxDjd+KweU6JS8DiRv0gIhCIqCdZ2ALPH+JqcqOq+QaUYp36ehm62zDQLJyQDM2IsPUej4q1GQ5zbhF+Rvj0rRrkyG/pKSqzTtwXu5r+dmzz2/bagvdNM51pspgTgND7NTxT6q2C/ps2A7ayahd7iySxnfThhYnzAlshITkYEIDDhBzz+dJlRINFY+wtbbomW/On/6IqaNBiWVb1bk/VYswfaDRLrhzNnsQ5IU7OkR2gfVNyH9/ck5K2Au7YXTXWfpxLzSxBfhTvEBaOmWY4CTU/jbTvbpuGavy3HNMEChq+FATMmfG0+bvD0lkYhBau9ShG+DtC9rQCKacZt/wZ3kObvvB0g/8RLaEddgPfHKTTl8PS+fomhRwSF4L6IJdZqSAueuIab3hdi3CUwgGHqGXfAOwZRNVu6AphwsNV1bEocwK5SsBBCEztM9y66eH7cPPllrajpLxbQn2aM9ZTF3KBP/uWyyoE27e370Odmgr9LZ1sZfIzkF6ETGzCfrJTJGIXJ2qNXXdE2WA39so=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
